dist: trusty

language: rust

sudo: true

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - libiberty-dev
            - g++

os:
    - linux

rust:
    - beta

env:
    matrix:
        - ARCH=x86_64

install:
    - rustc -vV
    - cargo -vV
    - mkdir -p ~/.cargo/bin
    - sh bin/install_kcov.sh
    - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$HOME/Library/Python/2.7/bin:$PATH
    - export RUSTFLAGS="-C link-dead-code"
    - kcov --version
    - cargo install cargo-kcov

script:
    - cargo test
    - cargo-kcov kcov --verbose --no-clean-rebuild --lib --coveralls
