dist: trusty

language: rust

sudo: true

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - libiberty-dev
            - g++

os:
    - linux

rust:
    - nightly

install:
    - rustc -vV
    - cargo -vV

    # Install kcov.
    - mkdir -p ~/.cargo/bin
    - sh src/install_kcov.sh
    - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$HOME/Library/Python/2.7/bin:$PATH
    - export RUSTFLAGS="-C link-dead-code"
    - kcov --version

script:
    - cargo build
    - cargo test
    - cargo run -- kcov --verbose --no-clean-rebuild --lib --coveralls