applications = "CustomApplication"
appMenus = "AppMenu"
autoResponseRules = "AutoResponseRules"
classes = "ApexClass"
cleanDataServices = "CleanDataService"
components = "ApexComponent"
duplicateRules = "DuplicateRule"
flexipages = "FlexiPage"
flowDefinitions = "FlowDefinition"
flows = "Flow"
homePageLayouts = "HomePageLayout"
labels = "CustomLabels"
layouts = "Layout"
objects = "CustomObject"
objectTranslations = "CustomObjectTranslation"
pages = "ApexPage"
profiles = "Profile"
quickActions = "QuickAction"
remoteSiteSettings = "RemoteSiteSetting"
roles = "Role"
sharingRules = "SharingRules"
tabs = "CustomTab"
topicsForObjects = "TopicsForObjects"
triggers = "ApexTrigger"